version: '3.1'

services:
  db:
    image: mariadb:10.3.15
    ports:
      - "14306:3306"
    environment:
      - "MYSQL_HOST=localhost"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=pass"
      - "MYSQL_ROOT_PASSWORD=pass"
      - "MYSQL_DATABASE=mariadb"
    volumes:
      - db-data-volume:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 100M
        reservations:
          cpus: '0.01'
          memory: 20M
volumes:
  db-data-volume: